FROM python:3.12.5-slim-bookworm

# Set environment variables for non-interactive setup and unbuffered output
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8 \
    PYTHONPATH="/app"

# Set working directory inside the container
WORKDIR /app

# Copy requirements to leverage Docker cache
COPY requirements.txt .

# Install dependencies without caching
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire application into container
COPY . .

# Define the container's startup command
ENTRYPOINT ["python3", "main.py"]
