name: fmu-runner-3
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to for simulation requests.
    defaultValue: simulation
    required: true
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write simulation results to.
    defaultValue: simulation-results
    required: true
  - name: S3_ENDPOINT
    inputType: FreeText
    description: S3/MinIO endpoint URL for fetching FMU model binaries.
    defaultValue: http://minio:80
    required: true
  - name: S3_ACCESS_KEY
    inputType: Secret
    description: S3 access key ID.
    defaultValue: s3_user
    required: true
  - name: S3_SECRET_KEY
    inputType: Secret
    description: S3 secret access key.
    defaultValue: s3_password
    required: true
  - name: S3_BUCKET
    inputType: FreeText
    description: S3 bucket name where FMU models are stored.
    defaultValue: fmu-models
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: fmu-runner
