name: minio
language: docker
variables:
  - name: MINIO_ROOT_USER
    inputType: Secret
    description: The root username to initialize Minio with
    secretKey: s3_user
    required: true
  - name: MINIO_ROOT_PASSWORD
    inputType: Secret
    description: The root password to initialize Minio with
    defaultValue: s3_password
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: minio
